from __future__ import annotations

from datetime import date
from typing import Protocol, Sequence

from hhpulse.domain.entities import AnalysisJob, CrawlRun, CrawlUnit
from hhpulse.domain.value_objects import SearchObservation


class AnalysisJobRepository(Protocol):
    async def add(self, job: AnalysisJob) -> None: ...

    async def get(self, job_id: str) -> AnalysisJob | None: ...

    async def list(self) -> Sequence[AnalysisJob]: ...

    async def update(self, job: AnalysisJob) -> None: ...


class CrawlRunRepository(Protocol):
    async def add(self, run: CrawlRun) -> None: ...

    async def get(self, run_id: str) -> CrawlRun | None: ...

    async def get_for_job_date(self, job_id: str, observation_date: date) -> CrawlRun | None: ...

    async def update(self, run: CrawlRun) -> None: ...


class CrawlUnitRepository(Protocol):
    async def add_many(self, units: Sequence[CrawlUnit]) -> None: ...

    async def list_for_run(self, run_id: str) -> Sequence[CrawlUnit]: ...

    async def list_incomplete_for_run(self, run_id: str) -> Sequence[CrawlUnit]: ...

    async def update(self, unit: CrawlUnit) -> None: ...


class ObservationRepository(Protocol):
    async def stage(self, run_id: str, unit_id: str, observation: SearchObservation) -> None: ...

    async def publish_run(self, run_id: str) -> None: ...

    async def discard_staging(self, run_id: str) -> None: ...
